// @see-also(drools 8): https://docs.drools.org/8.44.0.Final/drools-docs/drools/language-reference/index.html
package com.example.rules;

unit PersonRules2;

global org.slf4j.Logger logger;

import com.example.droolsdemo.model.Person;
import com.example.droolsdemo.util.RuleUtils

 rule "boyPlus"
 when
    $p : Person(sex == "boy")
 then
    logger.warn("trigger boy");
    $p.setAge($p.getAge() +100);
    logger.info("年龄增加100");
 end